[profile.default]
src = "l2_foundry/src"
test = "l2_foundry/test"
scripts = "l2_foundry/script"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]
